const products = [
  {
    title: "Men's Cotton Casual Shirt",
    description: "Comfortable cotton shirt for everyday style.",
    price: 1299,
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    brand: "Shopping Now",
    countInStock: 20,
    rating: { rate: 4.4, count: 120 },
  },
  {
    title: "Women's Red Dress",
    description: "Elegant red dress with a modern fit.",
    price: 2499,
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    brand: "Shopping Now",
    countInStock: 15,
    rating: { rate: 4.7, count: 88 },
  },
  {
    title: "Classic Backpack",
    description: "Durable backpack with roomy compartments.",
    price: 1799,
    category: "bags",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    brand: "Shopping Now",
    countInStock: 30,
    rating: { rate: 4.2, count: 210 },
  },
  {
    title: "Gold Plated Bracelet",
    description: "Polished bracelet for festive and casual wear.",
    price: 999,
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    brand: "Shopping Now",
    countInStock: 25,
    rating: { rate: 4.1, count: 64 },
  },
  {
    title: "Wireless Headphones",
    description: "Clear audio wireless headphones with soft ear cushions.",
    price: 3299,
    category: "electronics",
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    brand: "Shopping Now",
    countInStock: 18,
    rating: { rate: 4.5, count: 150 },
  },
];

export default products;
